.PHONY: apollo

define SENSORS_MIGRATION_SCRIPT
CREATE TABLE data
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sensor_id VARCHAR(32) NOT NULL,
    temp NUMERIC(7, 2) NOT NULL,
    context JSON DEFAULT '{}',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    synced_at TIMESTAMP WITH TIME ZONE NULL
);
CREATE INDEX created_at_index ON data (created_at DESC);
endef

export SENSORS_MIGRATION_SCRIPT
migrate:
	export PGPASSWORD=apollo
	psql -h localhost -U apollo apollo -c "$$SENSORS_MIGRATION_SCRIPT"

pip:
	uv pip install -r requirements.txt

update:
	pcu requirements.txt -u
	pre-commit autoupdate

check:
	git add .
	pre-commit run

test:
	export LOG_PATH=/tmp/odin.log && pytest

deploy:
	GLOBIGNORE="(*.pyc|*.jpg)" scp -r [!.]* coruscant:/home/manti/app/
